src/CowSdk.ts
src/utils/common.ts

There were 2 issues related with the latest changes that needed to be addressed before publishing

Fix typescript definition files output again and remove generic from updateChain method

---

package.json
src/api/cow-subgraph/graphql.ts
src/api/cow/cow.spec.ts
src/utils/tokens.spec.ts

Closes #20 
This PR improve coverage of API methods + Some utils functions
Coverage reaches `≈85%`
The lines were not covered are related to some edge cases really difficult to test. We are not using those in our API methods.

Improve coverage

---

src/api/cow/types.ts

Useful exports of utils price types

[types] Export price util types

---

package.json
src/api/cow/cow.spec.ts
src/api/cow/index.ts
src/api/cow/types.ts
src/constants/index.ts
src/types/index.ts
src/utils/sign.ts
yarn.lock

This PR just changes the dependency on `@gnosispm/gp-v2-contracts` to `@cowprotocol/contracts`, since that the new NPM package that we are using 😄.

Use `@cowprotocol`-Scoped Dependency

---

src/api/cow-subgraph/graphql.ts
src/api/cow-subgraph/index.ts
src/api/cow/index.ts
src/constants/chains.ts
src/constants/index.ts
src/constants/tokens.ts

Part of the https://github.com/cowprotocol/cowswap/issues/416
This PR adds Goerli network

Added goerli network

---

package.json
yarn.lock

appdata RC.2 > RC.3 to fix exports

Update app-data to latest

---

docs/post-order-example.ts

Reported in https://github.com/cowprotocol/cow-sdk/issues/77

Fix example comment

---

package.json
src/api/cow-subgraph/graphql.ts
yarn.lock

Update app data version

---

src/api/cow/cow.spec.ts
src/api/cow/index.ts
src/api/cow/types.ts

Part of https://github.com/cowprotocol/explorer/issues/256
Transforming EthFlow related fields for EthFlow orders
Unit tests

Eth flow/explorer256 ethflow types

---

package.json
src/api/cow/types.ts

Adds `executedSurplusFee` which is nice expose in the API

Add executedSurplusFee

---

package.json
src/api/metadata/metadata.spec.ts
yarn.lock

```
"@cowprotocol/app-data": "^0.0.2-RC.0"
```
Includes `orderClass` parameter for `AppData`

Update app-data version

---

.github/workflows/cla.yml

Adds CLA
Follows instructions in https://github.com/cowprotocol/cla

CLA signatures

---

package.json
src/order-book/api.spec.ts
src/order-book/api.ts
src/order-book/generated/index.ts
src/order-book/generated/models/AppDataDocument.ts
src/order-book/request.ts

Just a test that uses the current implementation of the API. 
This PR is not meant to be merged, is just a small change on top of https://github.com/cowprotocol/cow-sdk/pull/131 (which is the one we should merge) so we can test to upload appData docs with the current implementation, but be ready for the change backend is currently doing https://cowservices.slack.com/archives/C0375NV72SC/p1690808436607429?thread_ts=1690297997.334099&cid=C0375NV72SC

Make a test RC

---

src/composable/ConditionalOrder.spec.ts
src/composable/ConditionalOrder.ts
src/composable/orderTypes/Twap.ts

Follow up on https://github.com/cowprotocol/cow-sdk/pull/159#discussion_r1312973751

Change spelling of authorized

---

package.json
src/composable/ConditionalOrder.spec.ts
yarn.lock

DONT_TRY_AGAIN when the we have an "Invalid Conditional Order"
This allows "Concrete order" validation to signal that the order is not correct (and never will!), so there's no point to polling again

[Polling tests] Validate concrete orders

---

src/composable/ConditionalOrder.spec.ts

This PR makes sure that, if the current order that the Conditional Order yields is already present in the Order Book API, then it returns TRY_NEXT_BLOCK instructing the watch tower to not post the order for this block, but re-attempt later. 
`yarn test`

Test order is in the orderbook case

---

src/composable/orderTypes/Twap.spec.ts
src/composable/orderTypes/Twap.ts

The Conditional Order id is super important piece of data, I think it should be part of the toString method. 
This PR adds it. 
Also, it adds some tests for the ID method in the TWAP order.

Add id in to toSting method

---

package.json
src/order-book/generated/index.ts
src/order-book/generated/models/AuctionOrder.ts
src/order-book/generated/models/CompetitionOrderStatus.ts
src/order-book/generated/models/PriceImprovement.ts
src/order-book/generated/models/Quote.ts

Apply https://github.com/cowprotocol/services/pull/2858

fix: update orderbook open api

---

README.md
package.json
src/common/chains.ts
src/common/configs.ts
src/order-book/api.ts
src/subgraph/api.ts

Add Base network
Unit tests (no changes)

feat: add base network

---

src/composable/orderTypes/Twap.ts

Ref: https://github.com/cowprotocol/cowswap/pull/5142#discussion_r1867393060

fix: do not add excessive parameters in `TwapData`

---

src/trading/appDataUtils.ts
src/trading/getQuote.ts
src/trading/postLimitOrder.ts
src/trading/postSwapOrder.test.ts
src/trading/types.ts

Partner fee parameter was ignored 🤦

fix(trading-sdk): add partner fee to app-data

---

package.json
src/composable/orderTypes/Twap.spec.ts
src/composable/orderTypes/Twap.ts

Cherry-pick changes in: https://github.com/cowprotocol/cow-sdk/pull/284
Make a new hotfix for latest stable version.

Fix t0 set to epoc v5

---

packages/trading/src/postCoWProtocolTrade.test.ts
packages/trading/src/postCoWProtocolTrade.ts
packages/trading/src/tradingSdk.ts

Implement automatic UTM tracking in cow-sdk following the issue:
https://github.com/cowprotocol/cow-sdk/issues/388

feat(UTM): add UTM tracking support for developer attribution

---

src/chains/details/bnb.ts

No function changes.
Add BNB bridge info.

fix(bnb): add bnb chain bridge info

---

README.md
packages/providers/viem-adapter/README.md

All READMEs validated
How it was done:
- All code examples from the READMEs were copied into a TypeScript file
- Syntax and imports were validated
Ensures the snippets are copy-paste functional

fix: update viem-adapter/README and root README
