.github/workflows/publish.yml, .gitignore, src/workflows/publish.sh
Attempt to fix publishing workflow to go straight to NPM rather than using internal gitlab setup.
Already added to repo secrets the env var `NODE_AUTH_TOKEN`
Copied workflow setup from https://github.com/cowprotocol/token/blob/main/src/workflows/publish.sh
=> Publishing workflow fix

src/index.ts
There were places on the Explorer where the enum was needed directly like in https://github.com/cowprotocol/explorer/blob/c9ee4f1ce2008e481d53dc30a7e61074672d41ea/src/const.ts#L232
=> Export SupportedChainId

README.md, src/api/metadata/index.ts, src/api/metadata/metadata.spec.ts, src/utils/context.ts, src/utils/ipfs.ts
This PR closes #5 
Added the following methods to complete metadata flow: 
- `generateAppDataDoc`
- `uploadMetadataDocToIpfs`
Besides, IPFS logic was moved to the SDK.
Unit tests were added to improve coverage
=> [Metadata API] Add methods left to complete metadata flow

src/api/metadata/index.ts, src/api/metadata/metadata.spec.ts, src/api/metadata/types.ts, src/schemas/appData.schema.json, src/utils/appData.spec.ts
Part of https://github.com/cowprotocol/cowswap/issues/332
Adding quote metadata as defined on [this doc](https://docs.google.com/document/d/1N8K-ueKxxuuFfKjnegbPUYx30Qk1H8zjeiLo3jg-X14/edit#)
In summary there's a new metadata key that we'll use to track original quote information with every order
Added the types, schema and unit tests
=> Cowswap 332/quote metadata

README.md, package.json, src/api/metadata/index.ts, src/api/metadata/metadata.spec.ts, src/api/metadata/types.ts, src/types/ipfs-only-hash.d.ts, src/utils/appData.ts, src/utils/ipfs.ts, tsconfig.json, yarn.lock
Part of https://github.com/cowprotocol/cowswap/issues/332
New method added `cowSdk.metadata.calculateAppDataHash`
Calculates appDataHash (and cidV0) for given appData doc.
Throws if the doc doesn't match the schema
Unit tests
=> Cowswap 332/generate doc hash

src/api/cow/errors/OperatorError.ts, src/api/cow/errors/QuoteError.ts, src/api/cow/index.ts, src/utils/appData.spec.ts, src/utils/common.ts, src/utils/sign.ts
This PR closes #10 
Removed ESlint warnings by updating data types.
--
There's only one `any` type in `_signPayload` function that I was not able to get rid out so I commented the line. The thing is we could receive two different functions in `signFn` param with different payload data, which causes typing mismatch.
=> Remove ESlint warnings

src/api/cow/cow.spec.ts, src/api/cow/index.ts, src/api/cow/types.ts, src/types/utilities.d.ts
The orderId param was left behind and it was never added to the getTrades method, to [simplify things](https://github.com/cowprotocol/explorer/blob/35-epic-home-page/src/api/operator/operatorApi.ts#L161) on the Explorer we need this change
Would fix https://github.com/cowprotocol/explorer/issues/118
=> Add orderId param to getTrades method

README.md, src/CowSdk.ts, src/api/cow-subgraph/graphql.ts, src/api/cow/cow.spec.ts, src/api/cow/index.ts, src/api/cow/types.ts, src/utils/context.ts
This PR closes #30 
We've added some new improvements to the SDK: 
- The possibility of instantiating the SDK without passing `chainId` as argument. It will default to `Mainnet`.
- The possibility of overriding default params (chainId and env) for every method in `CowApi` .
- When query is not paginated, we will get data from both envs (barn and prod) if the environment is not set in the method params.
=> SDK improvements

src/utils/appData.spec.ts, src/utils/appData.ts
- Refactoring app data tests
- Removed a bunch of appData schema tests. Those are being added to https://github.com/cowprotocol/app-data/pull/5
- Added unit tests specific to the validation fn
- Grouped/wrapped tests in `describe`
- Throwing CowError when trying to load/validate an appData schema version that doesn't exist
- Fixing ajv errors not being passed down
Built on top of https://github.com/cowprotocol/cow-sdk/pull/50
Unit tests
=> Refactor app data tests

.babelrc, babel.config.js, package.json, src/api/base/index.ts, src/constants/index.ts, yarn.lock
Close #36 
Tested locally using https://github.com/ramirotw/cow-sdk-nodejs/tree/es6-import
=> Support modules in nodejs

README.md, package.json, src/CowSdk.ts, src/api/metadata/index.ts, src/api/metadata/metadata.spec.ts, src/utils/appData.spec.ts, src/utils/appData.ts, yarn.lock
- Exposing new methods on metadata api:
- `getAppDataSchema`
- `validateAppDataDoc`
- Refactored appData and metadata unit tests
Unit tests
=> Expose metadata methods from app data

.gitignore, package.json, src/api/cow-subgraph/graphql.ts, src/api/cow/cow.spec.ts, src/api/cow/index.ts, src/api/cow/types.ts
This PR tries to solve some issues that arrises when you try to use the SDK to get a quote.
I only tried to solve two issues:
- The current params for the quote method are out of sync with the API. For example, they require an `amount` when now the API allows to specify the limit order in 3 different ways:
(1) sell order where you input the sell amount before fees (`sellAmountBeforeFee`)
(2) sell order where you input the sell amount after fees (`sellAmountAfterFee`)
(3) buy order where you input the sell amount after fees (`buyAmountAfterFee`)
With the v0.0.15, you can only provide the `amount`. This PR re-exposes the original signature, so you can especify the order in any of these 3 methods.
- If you provide the wrong parameters, the backend sometimes will fail to parse the input. If …
=> Handle non-json errors and expose original quote API

.babelrc, __mocks__/paraswap.js, package.json, src/CowSdk.ts, src/api/0x/0x-quote.spec.ts, src/api/0x/error/0x-error.spec.ts, src/api/0x/index.ts, src/api/0x/utils.ts, src/api/paraswap/constants.ts, src/api/paraswap/error/index.ts, src/api/paraswap/index.ts, src/api/paraswap/paraswap.spec.ts, src/api/paraswap/types.ts, src/api/paraswap/utils.ts, yarn.lock
Part of adding the 0x and Paraswap apis
Adds:
1. ParaswapApi
2. ParaswapError
3. tests
* Tests run a mocked version of the `node_modules/paraswap` sdk as they don't use fetch (so no easy stubbing)
* Adds a simple Error class similar to the others
`yarn test --testRegex "paraswap.spec.ts"`
=> Add ParaswapApi + ParaswapError

src/CowSdk.ts, src/api/0x/0x-quote.spec.ts, src/api/0x/error/0x-error.spec.ts, src/api/paraswap/paraswap.spec.ts, src/types/index.ts, src/types/sdk.ts, src/types/utilities.d.ts, yarn.lock
Properly fixes the CowSdk implementation type to account for the optional APIs
- fixes tests as well
This allows us to do sth like:
```ts
const sdk = new CowSdk(
1,
{},
{
zeroXOptions: {
enabled: true,
},
paraswapOptions: {
enabled: false, // this is default
},
}
)
```
which the TS compiler will return:
*ZeroXApi enabled* & *ParaswapApi disabled*
meaning no more need for property assertions (`props!.thing`) or optional chaining (`prop?.thing`)
=> CowSdk - fix constructor type for optional APIs (and tests)

src/CowSdk.ts, src/api/0x/0x-quote.spec.ts, src/api/0x/error/0x-error.spec.ts, src/api/0x/index.ts, src/api/0x/types.ts, src/api/0x/utils.ts, src/api/paraswap/index.ts, src/api/paraswap/paraswap.spec.ts, src/api/paraswap/types.ts, src/types/index.ts, src/types/sdk.ts, src/types/utilities.d.ts, yarn.lock
CowSdk has options parameter to enable `ZeroXApi` and `ParaswapApi`
1. Adjusts tests
2. Small update to `ParaswapApi` constructor to allow passing options
3. Rename instances of `Matcha` to be `ZeroX`
=> CowSdk options params to enable 0x and Paraswap APIs

package.json, src/api/cow-subgraph/cow-subgraph.spec.ts, src/api/cow-subgraph/index.ts, src/api/cow/cow.spec.ts, src/api/cow/index.ts, src/api/cow/types.ts, yarn.lock
* Add the Options object to the subgraph API to change the network and environment on each method call
* Add mainnet and gc staging endpoints to the subgraph API
* Remove unneeded pagination for the [`/trades` endpoint](https://api.cow.fi/docs/#/default/get_api_v1_trades)
* Fixes a `StrictUnion` import which [caused issues](https://github.com/cowprotocol/cow-sdk/issues/36#issuecomment-1208288514)
=> Add Staging to the subgraph API & other fixes

.github/workflows/publish.yml, src/workflows/publish.sh
As discussed, we should be publishing npm packages when creating new releases and not doing it manually to avoid losing sync between npm versions and releases as we have now with `1.0.0-RC.0`
=> Trigger npm publish when a release/pre-release is created

src/workflows/publish.sh
There's an issue in the string comparison of latest_tag which caused the script to try to run `latest_tag` string as a command.
Same as https://github.com/cowprotocol/app-data/pull/14
=> Fix string comparison in publish script

.editorconfig, src/api/cow/index.ts, src/api/cow/orderTransform.ts, src/api/cow/transformOrder.ts, src/api/cow/types.ts
#Fixes: https://github.com/cowprotocol/cowswap/issues/1348
Based on: https://github.com/cowprotocol/cowswap/pull/1588#discussion_r1037501631
For limit-orders we should take `executedSurplusFee` as total fee amount and fallback to `executedFeeAmount`
=> Calculate totalFee for orders

package.json, yarn.lock
Fixes #91 
Bumping app-data pkg to `0.0.3-RC.0`
For more context see https://github.com/cowprotocol/app-data/pull/21
1. Unit tests with `yarn test`
2. Publish it locally with `yalc`: `yalc publish`
3. Check and installs deps locally the [cow-sdk-app](https://github.com/adamazad/cow-sdk-app) project: `npm i`
4. Add local sdk copy with yalc: `yalc add @cowprotocol/cow-sdk`
5. Build it: `npm run build`
* Should succeed
6. Run the app: `npm run start`
* Should start fine
=> Bumped app-data to v0.0.3-RC.0 to fix #91

package.json, yarn.lock
`ethers` - should be in "devDependencies" because we need it only for unit-tests
`@ethersproject/abstract-signer` - is used only on types checking level, so, it's ok to have it in "dependencies"
=> Fix npm dependencies types

package.json, src/order-book/api.ts, src/order-book/transformError.ts
In exponential backoff, not having the raw error body limits us in terms of determining when to retry or not (i.e. not knowing the status).
This change adds a transformation function and applies it to getQuote as a PoC. (And to fix https://github.com/cowprotocol/cowswap/issues/2311)
=> Add error transformer to add rawApiError to quote rejection

package.json, src/order-book/api.ts
Adds rawApiError to native price quote endpoint, to be able to backoff earlier.
=> Add rawApiError to native price quote

package.json, src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/orderTypes/Twap.ts, src/composable/types.ts, src/composable/utils.ts
This PR 
This params allow the `poll` method to use either the `blockNumber` or the `blockTimestamp` to validate the concrete Conditional Order.
It will check if the order started. If it haven't then we can signal we don't want to re-check until the start time
This is causing a lot of noise in the logs. Expired TWAP orders are never deleted. Now they are
Tried it in WatchTower (adapted it in https://github.com/cowprotocol/tenderly-watch-tower/pull/16)
Handled errors should not show as errors
Left some notes for a future PR on something that will help to reduce significantly the number of checks we need to do.
It's out of scope cause is not a trivial change. It will need a model update in watch tower
=> Handle Expired TWAP and not started TWAP

src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts
This PR just restructures the tests.
In my opinion, tests should assert one thing. This will make it easier to understand the scope, maintain, and know exactly what is wrong when tests start to fail.
For this reason, I reorganized the tests (in anticipation to the fact I want to create a new PR with new tests)
=> Twap test structure

src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/contracts.ts, src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts, src/composable/orderTypes/index.ts, src/composable/types.ts
This PR:
1. Fixes various typos in the composable section of the code base.
2. Adjusts some nomenclature for non-exported variables.
3. Fixes a typo in an exported const that affects downstream consumers (comments inline in code).
=> fix: typos and nomenclature

package.json
Add global import support for jest
it was possible before to use global import (instead of relative) for any TS code, but not in tests.
This makes the test to break as soon as you use something with a global import.
This PR fixes this.
=> Add global imports for jest

src/composable/ConditionalOrder.spec.ts, src/composable/contracts.ts, src/composable/orderTypes/test/TestConditionalOrder.ts
This PR mocks the ConditionalOrders tests, so we can run some unit tests that involves calls to the contract.
The new methods, like `poll` and `cabinet` will require this mocking.
This PR also adds the unit test for the `cabinet`
=> Mock contracts and test cabinet

src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/Multiplexer.ts, src/composable/orderTypes/Twap.ts, src/composable/orderTypes/test/TestConditionalOrder.ts, src/composable/types.ts
This PR includes the mocking and testing of the `poll` method. 
For now, only the following tests:
-  Happy path: getTradeableOrderWithSignature doesn't revert, and the order don't have any validation errors
- Not auth: the owner hasn't authorised the order
=> Test poll happy path and not authorized

src/composable/ConditionalOrder.spec.ts
Normally, validations, if done right, will catch all errors and return a comprehensive error.
This is why, by the time we do the call to `getTradeableOrderWithSignature` we will have quite some certainty the call will succeed. If it doesn't we will consider it an `UNEXPECTED_ERROR` and will return the original error with the result. 
This PR adds a unit test to validate we get this result in this situation.
=> [Polling tests] Add Handle unexpected errors

src/composable/orderTypes/Twap.ts
This PR:
1. Optimises the end timestamp for TWAPs when `span != 0` (ie. durationType != AUTO).
2. Closes #164
=> fix: end timestamp when span not 0

src/composable/ConditionalOrder.spec.ts, src/composable/orderTypes/Twap.ts, src/composable/orderTypes/test/TestConditionalOrder.ts
This PR verifies that the child class always have the last word when we are polling, and can signal what should be the result.
It adds 6 new tests for the different outcomes of `pollValidate`:
The tests were a bit repetitive, so for this one i created a shared function. After all, i just want to test for all case, the `poll` will respect what the `pollValidate` says, so i just want to see it handles expectations, and all the result codes.
Note that I had to extend the test order class to be able to override and mock `pollValidate` (its protected, which makes it harder to mock)
=> Mock class and implement custom polling test

src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/Multiplexer.ts, src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts, src/composable/orderTypes/test/TestConditionalOrder.ts, src/composable/utils.ts, src/order-book/__mock__/api.ts, src/utils.ts
This PR adds a 2 things:
1) A new check, after we get the order that "should" be created, we double-check if it was already created or not by quering the orderbook.
2) After we verify the existence of the order, the polling will return by default `TRY_NEXT_BLOCK`, but at the same time it will give the concrete order to give a different result. This will allow orders like Twap to say: "Ok, so if current part is already created, next part should be starting by this exact time, therefore it will return a `TRY_AT_EPOCH` overriding `TRY_NEXT_BLOCK` default). 
This will allow orders to be polled much more efficiently, for example, DCA that trades once a month, you will not need to check every block between two months.
Also, another efficiency, is that watch towers will not need to post the …
=> Check existence of the order in the orderbook, and add polledOrderInOrderbook

src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts
This PR test the “poll validate” logic, which is how the abstract order asks the concrete order to validate.
The tests will cover the cases where:
- The order has not started: It will instruct Watch Tower to wait until the correct start time
- The order has expired: It will instruct the Watch Tower to not poll again this order. Expired orders, won’t yield a valid order since it is a final state
- It also asserts the logic of not passing the blockInfo, so it uses the latest block info
`yarn test`
=> Test twap poll validate

src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts
This PR implements and test the logic in TWAP that instructs the watch-towers what is the next polling time for the case, the current part is already in the order book. 
This is very important for the scalability of watch towers, since otherwise they would need to check on every block.
This PR will allow a DCA that executes once a month, to be polled only once a month (two at most, since first polling returns the current part, and next polling for the same period will instruct to wait for approximately one month )
The test will cover various edge cases in the execution of a 10 parts TWAP order. Read the tests for more details. As a summary:
- Will verify that when is the time of part N, it instructs watch tower to wait until N+1 starts
- Will verify that if we are in the last part, then …
=> Handle twap in orderbook

package.json, src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/Multiplexer.spec.ts, src/composable/Multiplexer.ts, src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts, src/composable/orderTypes/test/TestConditionalOrder.ts, src/composable/utils.spec.ts, src/composable/utils.ts, tsconfig.json
This PR tries to close the SDK release v3.0.0
For that, I'm ensuring the Tenderly Watch Tower project works great with this version. 
This PR does some small MISC in order to consider 3.0.0 ready!
The compute UID was not working. 
The struct needs be converted into an order (mapping some fields). 
Created some util to convert order structs to orders.
Additionally, I did some unit test for it. 
toString is traditionally used to ready in the logs the details of the object. I felt it was a bit hard to read the older version, plus logging tools have a harder time parsing the values to make it easier to search
Also, the toString was not including some fields, like the receiver or the appData.
For this reason, I modified the implementation to serialise a JSON describing the TWAP:
Before:
After: …
=> Misc and close SDK version

src/composable/orderTypes/Twap.spec.ts, src/composable/orderTypes/Twap.ts
**Problem**
Previously, the guard for an `epoch` of zero wasn't triggering as the return value of the cabinet was of type `BigNumber` and the `number` comparison to `0` would never trigger due to not being of type `number`.
**Solution**
This PR correctly handles the bignumber to number marshalling and guards against out-of-range conditions. As there is an interface requirement for the cabinet to be set if the order is of start mining time type, any order that doesn't meet this is requirement is automatically removed from the watch-tower.
=> fix: cabinet comparitor

src/composable/ConditionalOrder.ts, src/composable/types.ts
This PR will allow us to override any config param of the orderbook API for polling.
This will allow us to set our own endpoints
=> chore: allow to override orderbook API config for polling

README.md
This PR:
1. Adjusts the `README.md` to only use full `href`. This is to ensure links work on `typedoc` generated docusaurus.
=> fix: full href

package.json, src/subgraph/api.ts
Since not all networks have Subgraph support we need to explicitly define which networks have support.
To do this, I've changed type of `SUBGRAPH_PROD_CONFIG` and `SUBGRAPH_STAGING_CONFIG`.
Now the type is `string | undefined`, `undefined` means that Subgraph is not supported for the network.
=> feat(subgraph): explicitly define which networks are supported for Subgraph

package.json, src/composable/ConditionalOrder.spec.ts, src/composable/ConditionalOrder.ts, src/composable/types.ts
This PR:
1. Modifies the `PollParams` type to take an already-instantiated `OrderBookApi`.
**NOTES:** As this is a change to the type, this is a breaking change and is accompanied by a major version bump.
=> chore: preconfigured orderbook

README.md, examples/cra/src/pages/getQuote/index.tsx, examples/cra/src/pages/quickStart/index.tsx, examples/cra/src/pages/smartContractWallet/const.ts, src/common/chains.ts, src/common/configs.ts, src/common/consts.ts, src/order-book/api.ts, src/order-signing/orderSigningUtils.ts, src/subgraph/api.spec.ts, src/subgraph/api.ts
Remove Goerli from supported networks
- Unit tests
- Publish a local version and test it on cowswap
=> feat!: remove goerli

README.md, package.json, src/common/chains.ts, src/order-book/api.ts, src/order-book/generated/models/AuctionOrder.ts, src/subgraph/api.ts, yarn.lock
Part of https://github.com/cowprotocol/cowswap/issues/4310
Add Arbitrum
=> feat: add arbitrum

README.md, src/common/chains.ts, src/order-book/api.ts, src/subgraph/api.ts
Rename chain id from `ARBITRUM` to `ARBITRUM_ONE`
I did not follow the new recommendations and did not use the proper chain name format.
=> fix: rename chain id from ARBITRUM to ARBITRUM_ONE

package.json, src/order-book/quoteAmountsAndCostsUtils.ts
I just messed up with formula 🤦‍♂️
Instead of `fee = amount * percent / 100` I did `fee = amount / percent`
=> fix: fix partner fee amount calculation

src/cow-shed/CoWShedHooks.ts, src/cow-shed/contracts.ts
CoW-shed was using absolute imports in some places which causes the generated types to not find the the proper imports.
Changed it to relative.
This is causing the watch-tower `tsc` command to fail: https://github.com/cowprotocol/watch-tower/actions/runs/11722358815/job/32651723873?pr=162
In this lib all tests were passing as before.
The issue was when importing it on watch-tower.
I built it with `yalc`, published locally and installed onto watch-tower.
After that the build was successful.
=> fix: cow-shed types

src/composable/ConditionalOrderFactory.ts
We are observing some issues handling some TWAP orders in the logs.
According to the log, this message should only be shown for legacy polling, meaning that the order was not recognised as a known one, and instead of using the SDK polling for Conditional Orders, its using the generic polling of the Watch Tower.
The check if the order is a known one is based on the `ConditionalOrderFactory` who instanciates conditional orders based on their handler. 
I can see in the error the handler is TWAP, but it was not instantiated using the SDK which I believe it means the handler was not recognised. 
This PR makes the `ConditionalOrderFactory` to not be case sensitive, because otherwise it depends on the casing of the handler if its recognised or not. With this, the legacy polling should not be …
=> feat: make the conditional order factory case insensitive

docs/architecture.md, package.json, src/order-book/generated/index.ts, src/order-book/generated/models/Auction.ts, src/order-book/generated/models/AuctionPrices.ts, src/order-book/generated/models/CompetitionOrderStatus.ts, src/order-book/generated/models/ExecutedProtocolFee.ts, src/order-book/generated/models/OnchainOrderData.ts, src/order-book/generated/models/OrderCreation.ts, src/order-book/generated/models/OrderMetaData.ts, src/order-book/generated/models/OrderParameters.ts, src/order-book/generated/models/OrderQuoteRequest.ts, src/order-book/generated/models/OrderQuoteResponse.ts, src/order-book/generated/models/OrderQuoteSide.ts, src/order-book/generated/models/PriceQuality.ts, src/order-book/generated/models/ProtocolAppData.ts, src/order-book/generated/models/SolverSettlement.ts, src/order-book/generated/models/UID.ts, src/order-book/transformOrder.test.ts, src/order-book/transformOrder.ts
As part of backend's fee overhaul, `executedSurplusFee` is deprecated in favor of `executedFee`.
This change replaces it where applicable, as well as building the types based on the latest backend release that includes such changes https://github.com/cowprotocol/services/releases/tag/v2.291.0
- Unit tests
- Locally loaded it via `yalc` on CoW Swap/Explorer
=> feat: replace the usage of `executedSurplusFee` with `executedFee`

src/trading/getQuote.ts, src/trading/postCoWProtocolTrade.test.ts, src/trading/postCoWProtocolTrade.ts, src/trading/postSwapOrder.test.ts, src/trading/postSwapOrder.ts, src/trading/tradingSdk.ts, src/trading/utils.ts
Fixes first issue from [the doc.](https://docs.google.com/document/d/1KvTXmYj-aCBPr-YzgHqIJfZnn6H3Q4EejVl27VdKTZs/edit?tab=t.0)
This change fixes both sell and buy orders.
It also fixes "Private Key example not working" issue.
Basically, I reverted this commit: https://github.com/cowprotocol/cow-sdk/pull/213/commits/718b2123fbb74856c3ddcecadd9ed8bbcb12b833
Unfortunately, I don't remember why I did this :( 
But obviuosly this logic is wrong, because it adds fees + slippage twice:
- once in `swapParamsToLimitOrderParams`
- and another one in `getOrderToSign` (getQuoteAmountsAndCosts call)
I compared the result with CoW Swap and it matches 100%.
How to test that:
1. Copy `quoteResponseMock` from unit test
2. Go to `apps/cowswap-frontend/src/api/cowProtocol/api.ts` in CoW Swap
3. Return the …
=> fix(trading-sdk): fix order amounts calculations

src/trading/consts.ts, src/trading/postCoWProtocolTrade.test.ts
https://docs.google.com/document/d/1KvTXmYj-aCBPr-YzgHqIJfZnn6H3Q4EejVl27VdKTZs/edit?tab=t.0#heading=h.m2n3ppp9tinj
=> fix(trading-sdk): chane default order validity to 30min

src/trading/README.md
Fixes: https://docs.google.com/document/d/1KvTXmYj-aCBPr-YzgHqIJfZnn6H3Q4EejVl27VdKTZs/edit?tab=t.0#heading=h.sx52nbp2bvrz
1. Added info about `enableLogging` option
2. Updated default `validFor` value
3. Changed the methods order to make `getQuote -> confirm -> swap` first
4. Simplified the docs language
=> docs: update and simplify TradingSDK docs

src/composable/ConditionalOrder.ts, src/composable/utils.ts, src/trading/getEthFlowTransaction.test.ts, src/trading/getEthFlowTransaction.ts, src/trading/getPreSignTransaction.test.ts, src/trading/getPreSignTransaction.ts, src/trading/postSellNativeCurrencyOrder.test.ts, src/trading/postSellNativeCurrencyOrder.ts, src/trading/tradingSdk.ts, src/trading/types.ts, src/trading/utils.ts
Fixes https://docs.google.com/document/d/1KvTXmYj-aCBPr-YzgHqIJfZnn6H3Q4EejVl27VdKTZs/edit?tab=t.0#heading=h.e68ykbfkaz2q
Three problems were fixed:
1. `sellToken` parameter needs to be replaced by wrapped ETH when we make a quote request for eth-flow. But after getting a quote it must be put back to ETH address. Because of that I've added `getTradeParametersAfterQuote()` function
2. `gas` -> `gasLimit` renaming
3. Added `chainId` parameter to `getEthFlowTransaction` function because a signer might be just a private key, which doesn't provide `getChainId()` method
1. Go to `examples/vanilla` and run `yarn start`
2. Connect a wallet and setup a trade like on the picture bellow
3. Click "Get quote"
4. Click "Send order"
=> fix(trading-sdk): fix eth-flow

examples/vanilla/src/tokens.ts, package.json, src/chains/details/polygon.ts
This PR temporarily reverts commit `219ab33` ("feat: add more tokens to Avalanche and Polygon") from the `SDK-AGNOSTIC-LIB` branch.
That commit was added directly to `main`, and the `SDK-AGNOSTIC-LIB` branch was later created from `main`, causing it to inherit this change. Since our `bleu/refactor` branch was created earlier (without this commit), all PRs from our refactor work were running into unnecessary conflicts.
By reverting this commit temporarily, we avoid conflicts across multiple PRs. The original change will be restored when we complete the refactor and merge everything back into `main`, which already contains this commit.
This is a safe and temporary solution to simplify the ongoing development and review process.
This reverts commit 219ab33a560fd3800092e2db16098431cef2196e.
=> Chore(sdk-agnostic-lib): Revert "feat: add more tokens to `Avalanche` and `Polygon` (#320)"

packages/bridging/src/BridgingSdk/BridgingSdk.ts, packages/bridging/src/README.md, packages/common/README.md, packages/sdk/README.md, packages/trading/README.md
1. Added `adapter` parameter to `BridgingSdk` constructor
2. Updated `common`, `umbrella`, and `TradingSDK` docs to use `ViemAdapter` by default in the examples
=> fix: add adapter param to BridgingSdk and update docs

packages/common/src/adapters/AbstractProviderAdapter.ts, packages/common/src/adapters/types/AdapterUtils.ts, packages/common/src/adapters/types/index.ts, packages/contracts-ts/src/settlement.ts, packages/providers/ether-v5-adapter/src/EthersV5Adapter.ts, packages/providers/ether-v5-adapter/src/EthersV5Utils.ts, packages/providers/ether-v6-adapter/src/EthersV6Adapter.ts, packages/providers/ether-v6-adapter/src/EthersV6Utils.ts, packages/providers/viem-adapter/src/ViemAdapter.ts, packages/providers/viem-adapter/src/ViemUtils.ts, turbo.json
- **Adapter Handling**: 
- Ethers v5/v6: Work directly with common interface (permissive)
- Viem: Requires boundary conversion in adapter (strict branded types)
- **Impact**: Improved documentation while maintaining adapter flexibility through boundary conversion pattern
- 
**Problem**: When changed from `unknown` to specific type, breaks compatibility at multiple levels:
- **AdapterUtils Interface Conflict**: Methods like `verifyMessage(signature: SignatureLike)` and `verifyTypedData(signature: SignatureLike)` narrow the contract
- **Implementation Mismatch**: 
- EthersV5/V6Utils expect `BytesLike` (string | Uint8Array | ArrayLike<number>)
- Viem expects `0x${string}` format
- No single union type satisfies all adapters without compatibility issues
- **Call-site Breaks**: Code that …
=> fix: improve unknown type

packages/contracts-ts/src/order.ts
Closes https://github.com/cowprotocol/cow-sdk/issues/522
Uses the exported ZERO_ADDRESS from common instead of adapter instance. Reduces burden on developer to set an adapter just to construct an OrderUid.
Note that all Adapters use the same ZeroAddress anyway. 
Longer term approach would be to remove the zero address from the adapter instance entirely so there is no confusion. Curious to know why its there to begin with.
=> Remove Unnecessary Adapter Instance
